name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build JAR
        run: mvn clean install

      - name: Run Java Program
        run: java -cp target/my-java-project-1.0-SNAPSHOT.jar com.example.HelloWorld
        working-directory: ${{ github.workspace }}