jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Display Current Directory
        run: |
          pwd
          ls -la
        working-directory: ${{ github.workspace }}

      - name: Build JAR
        run: mvn clean install